"""
Configuration for River Level Extreme Conditions Monitor
Generated by setup wizard on 2026-03-01 14:26:19
Config name: Bushmans
"""

# Monitoring locations (USGS site numbers)
MONITORING_SITES = ['03277200', '03292470', '03292494', '03294500']

# Location coordinates (for finding nearby gauges)
LOCATION = {
    "latitude": 38.2542376,
    "longitude": -85.759407,
}

# Search radius for nearby gauges (in miles)
SEARCH_RADIUS_MILES = 50

# Extreme condition thresholds (percentiles)
# Values below LOW_FLOW_PERCENTILE are considered drought/low flow
# Values above HIGH_FLOW_PERCENTILE are considered flood/high flow
LOW_FLOW_PERCENTILE = 10  # Bottom 10%
HIGH_FLOW_PERCENTILE = 90  # Top 10%

# Alert thresholds for very extreme conditions
VERY_LOW_PERCENTILE = 5   # Severe drought
VERY_HIGH_PERCENTILE = 95  # Severe flood

# Parameter codes
# 00060 = Discharge (streamflow) in cubic feet per second
# 00065 = Gage height in feet
PARAMETER_CODE = "00065"  # Gage height (water level)

# Historical data range for calculating statistics
HISTORICAL_START_YEAR = 1980
