"""
Configuration for River Level Extreme Conditions Monitor
Generated by setup wizard on 2026-02-14 13:15:11
Config name: config
"""

# Monitoring locations (USGS site numbers)
MONITORING_SITES = []

# Location coordinates (for finding nearby gauges)
LOCATION = {
    "latitude": 38.442857,
    "longitude": -85.6620314,
}

# Search radius for nearby gauges (in miles)
SEARCH_RADIUS_MILES = 25

# Extreme condition thresholds (percentiles)
# Values below LOW_FLOW_PERCENTILE are considered drought/low flow
# Values above HIGH_FLOW_PERCENTILE are considered flood/high flow
LOW_FLOW_PERCENTILE = 10  # Bottom 10%
HIGH_FLOW_PERCENTILE = 90  # Top 10%

# Alert thresholds for very extreme conditions
VERY_LOW_PERCENTILE = 5   # Severe drought
VERY_HIGH_PERCENTILE = 95  # Severe flood

# Parameter codes
# 00060 = Discharge (streamflow) in cubic feet per second
# 00065 = Gage height in feet
PARAMETER_CODE = "00060"  # Discharge

# Historical data range for calculating statistics
HISTORICAL_START_YEAR = 1980
